version: '3.9'

services:
  skillwill_app:
    container_name: skillwill_app
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: sh ./start.sh development
    ports:
      - '${APP_PORT}:5000'
    env_file:
      - .env
    depends_on:
      - skillwill_pg
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - skillwill

  skillwill_pg:
    image: postgres:15
    container_name: skillwill_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - skillwilldata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - skillwill
    restart: unless-stopped

networks:
  skillwill:
    driver: bridge
volumes:
  skillwilldata:
    driver: local
